<b>Codes to clean the Population data.
</div>

In [1]:
# Start by importing required modules
import os
import pandas as pd

%matplotlib inline

In [2]:
# Define the directory path where the CSV file is located
directory_path = "Data_Input"

# Define the CSV file name
file_name = "Population_E_All_Data_NOFLAG.csv"

In [3]:
# Construct the full file path by joining the directory path and file name
file_path = os.path.join(directory_path, file_name)

In [4]:
# Import the required data
# A change in encoding type was needed due to an error in data loading for food file.
population_df = pd.read_csv(file_path,  encoding='latin-1')

In [5]:
# Have a quick look at the food dataframe
print(population_df.columns.is_unique)
print(population_df.shape)
print(population_df[population_df.duplicated() == True])
population_df.head()

True
(1323, 158)
Empty DataFrame
Columns: [Area Code, Area, Item Code, Item, Element Code, Element, Unit, Y1950, Y1951, Y1952, Y1953, Y1954, Y1955, Y1956, Y1957, Y1958, Y1959, Y1960, Y1961, Y1962, Y1963, Y1964, Y1965, Y1966, Y1967, Y1968, Y1969, Y1970, Y1971, Y1972, Y1973, Y1974, Y1975, Y1976, Y1977, Y1978, Y1979, Y1980, Y1981, Y1982, Y1983, Y1984, Y1985, Y1986, Y1987, Y1988, Y1989, Y1990, Y1991, Y1992, Y1993, Y1994, Y1995, Y1996, Y1997, Y1998, Y1999, Y2000, Y2001, Y2002, Y2003, Y2004, Y2005, Y2006, Y2007, Y2008, Y2009, Y2010, Y2011, Y2012, Y2013, Y2014, Y2015, Y2016, Y2017, Y2018, Y2019, Y2020, Y2021, Y2022, Y2023, Y2024, Y2025, Y2026, Y2027, Y2028, Y2029, Y2030, Y2031, Y2032, Y2033, Y2034, Y2035, Y2036, Y2037, Y2038, Y2039, Y2040, Y2041, Y2042, ...]
Index: []

[0 rows x 158 columns]

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y1950,Y1951,Y1952,...,Y2091,Y2092,Y2093,Y2094,Y2095,Y2096,Y2097,Y2098,Y2099,Y2100
0,2,Afghanistan,3010,Population - Est. & Proj.,511,Total Population - Both sexes,1000 persons,7752.118,7840.156,7935.997,...,76578.450,76448.747,76304.424,76146.060,75974.256,75789.684,75593.009,75384.981,75166.352,74937.964
1,2,Afghanistan,3010,Population - Est. & Proj.,512,Total Population - Male,1000 persons,4099.243,4134.756,4174.450,...,38233.156,38159.870,38080.223,37994.477,37902.920,37805.856,37703.619,37596.553,37485.029,37369.440
2,2,Afghanistan,3010,Population - Est. & Proj.,513,Total Population - Female,1000 persons,3652.874,3705.395,3761.546,...,38345.293,38288.875,38224.203,38151.583,38071.343,37983.823,37889.393,37788.419,37681.331,37568.521
3,2,Afghanistan,3010,Population - Est. & Proj.,551,Rural population,1000 persons,7286.991,7352.856,7425.363,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Afghanistan,3010,Population - Est. & Proj.,561,Urban population,1000 persons,465.127,486.654,509.617,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Delete unwanted columns Y2021-2100
population_df = population_df.loc[:,'Area':'Y2021']
population_df

,Area,Item Code,Item,Element Code,Element,Unit,Y1950,Y1951,Y1952,Y1953,...,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021
0,Afghanistan,3010,Population - Est. & Proj.,511,Total Population - Both sexes,1000 persons,7752.118,7840.156,7935.997,8039.694,...,31161.376,32269.589,33370.794,34413.603,35383.032,36296.113,37171.921,38041.754,38928.346,39835.428
1,Afghanistan,3010,Population - Est. & Proj.,512,Total Population - Male,1000 persons,4099.243,4134.756,4174.450,4218.336,...,15964.874,16554.278,17138.803,17686.166,18186.994,18651.985,19093.043,19529.727,19976.265,20434.981
2,Afghanistan,3010,Population - Est. & Proj.,513,Total Population - Female,1000 persons,3652.874,3705.395,3761.546,3821.348,...,15196.504,15715.314,16232.001,16727.437,17196.034,17644.126,18078.879,18512.030,18952.076,19400.447
3,Afghanistan,3010,Population - Est. & Proj.,551,Rural population,1000 persons,7286.991,7352.856,7425.363,7504.561,...,23280.663,23997.856,24703.798,25368.923,25985.093,26558.609,27099.874,27626.382,28150.604,28674.023
4,Afghanistan,3010,Population - Est. & Proj.,561,Urban population,1000 persons,465.127,486.654,509.617,534.035,...,7416.295,7733.832,8054.222,8367.571,8670.939,8971.472,9273.302,9582.625,9904.337,10239.684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1318,Net Food Importing Developing Countries,3010,Population - Est. & Proj.,511,Total Population - Both sexes,1000 persons,314112.506,320419.536,326963.216,333792.795,...,1400719.211,1431724.295,1463225.501,1495081.183,1527235.522,1559721.436,1592589.456,1625925.224,1659780.456,1694160.666
1319,Net Food Importing Developing Countries,3010,Population - Est. & Proj.,512,Total Population - Male,1000 persons,159439.502,162525.097,165737.209,169105.179,...,700414.399,715759.427,731381.401,747215.226,763235.070,779456.592,795903.664,812615.957,829615.408,846905.764
1320,Net Food Importing Developing Countries,3010,Population - Est. & Proj.,513,Total Population - Female,1000 persons,154571.136,157791.783,161122.379,164582.701,...,700173.121,715832.711,731711.306,747732.452,763866.300,780129.933,796550.264,813172.988,830028.036,847117.183
1321,Net Food Importing Developing Countries,3010,Population - Est. & Proj.,551,Rural population,1000 persons,268828.960,273233.039,277750.787,282434.076,...,892414.512,907197.471,921994.554,936713.837,951258.311,965617.589,979750.059,993672.027,1007388.355,1020878.341
1322,Net Food Importing Developing Countries,3010,Population - Est. & Proj.,561,Urban population,1000 persons,45298.102,47238.167,49279.891,51434.074,...,514639.848,531627.721,549072.030,566841.730,584963.723,603488.119,622474.988,641961.465,661978.510,682532.458

In [7]:
# Further delete unwanted columns
population_df.drop(
    columns=['Item Code', 'Item', 'Element Code', 'Unit', 'Y1950', 'Y1951', 'Y1952', 'Y1953', 'Y1954', 
             'Y1955', 'Y1956', 'Y1957', 'Y1958', 'Y1959', 'Y1960',], axis=1, inplace=True)

In [8]:
population_df

,Area,Element,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,...,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021
0,Afghanistan,Total Population - Both sexes,9169.410,9351.441,9543.205,9744.781,9956.320,10174.836,10399.926,10637.063,...,31161.376,32269.589,33370.794,34413.603,35383.032,36296.113,37171.921,38041.754,38928.346,39835.428
1,Afghanistan,Total Population - Male,4730.250,4816.050,4907.030,5003.245,5104.765,5210.122,5319.123,5434.458,...,15964.874,16554.278,17138.803,17686.166,18186.994,18651.985,19093.043,19529.727,19976.265,20434.981
2,Afghanistan,Total Population - Female,4439.156,4535.392,4636.170,4741.527,4851.553,4964.718,5080.813,5202.606,...,15196.504,15715.314,16232.001,16727.437,17196.034,17644.126,18078.879,18512.030,18952.076,19400.447
3,Afghanistan,Rural population,8370.731,8507.016,8649.566,8798.496,8954.064,9113.479,9276.202,9446.519,...,23280.663,23997.856,24703.798,25368.923,25985.093,26558.609,27099.874,27626.382,28150.604,28674.023
4,Afghanistan,Urban population,796.033,838.852,884.388,932.865,984.350,1038.852,1096.428,1157.827,...,7416.295,7733.832,8054.222,8367.571,8670.939,8971.472,9273.302,9582.625,9904.337,10239.684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1318,Net Food Importing Developing Countries,Total Population - Both sexes,401058.777,411026.339,421352.113,432064.927,443178.745,454720.867,466669.162,478930.067,...,1400719.211,1431724.295,1463225.501,1495081.183,1527235.522,1559721.436,1592589.456,1625925.224,1659780.456,1694160.666
1319,Net Food Importing Developing Countries,Total Population - Male,202692.031,207644.895,212771.490,218096.754,223635.155,229403.221,235386.339,241530.904,...,700414.399,715759.427,731381.401,747215.226,763235.070,779456.592,795903.664,812615.957,829615.408,846905.764
1320,Net Food Importing Developing Countries,Total Population - Female,198249.183,203263.082,208461.851,213848.924,219423.991,225197.531,231162.248,237278.080,...,700173.121,715832.711,731711.306,747732.452,763866.300,780129.933,796550.264,813172.988,830028.036,847117.183
1321,Net Food Importing Developing Countries,Rural population,328239.005,334985.012,341927.932,349102.908,356521.943,364242.909,372122.862,380122.167,...,892414.512,907197.471,921994.554,936713.837,951258.311,965617.589,979750.059,993672.027,1007388.355,1020878.341
1322,Net Food Importing Developing Countries,Urban population,73381.875,76721.391,80238.637,83934.411,87814.042,91852.917,96165.694,100675.008,...,514639.848,531627.721,549072.030,566841.730,584963.723,603488.119,622474.988,641961.465,661978.510,682532.458

In [9]:
# Rename the some of the column name
# Rename the remaining columns
population_df.rename(columns=lambda x: x[-4:] if x[0] == 'Y' else x, inplace=True)
population_df = population_df.rename(
    columns = {
        'Element': "Type", 'Area': 'Country'
        } 
)
population_df = population_df.set_index('Country')
population_df.head()
#crop_df.info()

,Type,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Total Population - Both sexes,9169.410,9351.441,9543.205,9744.781,9956.320,10174.836,10399.926,10637.063,10893.776,...,31161.376,32269.589,33370.794,34413.603,35383.032,36296.113,37171.921,38041.754,38928.346,39835.428
Afghanistan,Total Population - Male,4730.250,4816.050,4907.030,5003.245,5104.765,5210.122,5319.123,5434.458,5559.836,...,15964.874,16554.278,17138.803,17686.166,18186.994,18651.985,19093.043,19529.727,19976.265,20434.981
Afghanistan,Total Population - Female,4439.156,4535.392,4636.170,4741.527,4851.553,4964.718,5080.813,5202.606,5333.936,...,15196.504,15715.314,16232.001,16727.437,17196.034,17644.126,18078.879,18512.030,18952.076,19400.447
Afghanistan,Rural population,8370.731,8507.016,8649.566,8798.496,8954.064,9113.479,9276.202,9446.519,9630.541,...,23280.663,23997.856,24703.798,25368.923,25985.093,26558.609,27099.874,27626.382,28150.604,28674.023
Afghanistan,Urban population,796.033,838.852,884.388,932.865,984.350,1038.852,1096.428,1157.827,1223.887,...,7416.295,7733.832,8054.222,8367.571,8670.939,8971.472,9273.302,9582.625,9904.337,10239.684

In [10]:
# Fill the missing values with 0
population_df.fillna(value=0, inplace=True)
population_df.head()

,Type,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Total Population - Both sexes,9169.410,9351.441,9543.205,9744.781,9956.320,10174.836,10399.926,10637.063,10893.776,...,31161.376,32269.589,33370.794,34413.603,35383.032,36296.113,37171.921,38041.754,38928.346,39835.428
Afghanistan,Total Population - Male,4730.250,4816.050,4907.030,5003.245,5104.765,5210.122,5319.123,5434.458,5559.836,...,15964.874,16554.278,17138.803,17686.166,18186.994,18651.985,19093.043,19529.727,19976.265,20434.981
Afghanistan,Total Population - Female,4439.156,4535.392,4636.170,4741.527,4851.553,4964.718,5080.813,5202.606,5333.936,...,15196.504,15715.314,16232.001,16727.437,17196.034,17644.126,18078.879,18512.030,18952.076,19400.447
Afghanistan,Rural population,8370.731,8507.016,8649.566,8798.496,8954.064,9113.479,9276.202,9446.519,9630.541,...,23280.663,23997.856,24703.798,25368.923,25985.093,26558.609,27099.874,27626.382,28150.604,28674.023
Afghanistan,Urban population,796.033,838.852,884.388,932.865,984.350,1038.852,1096.428,1157.827,1223.887,...,7416.295,7733.832,8054.222,8367.571,8670.939,8971.472,9273.302,9582.625,9904.337,10239.684

In [11]:
## Delete region rows.
population_df.drop(
    index=['Africa','Americas', 'Asia', 'Australia and New Zealand', 'Belgium-Luxembourg', 
           'Caribbean', 'Central America', 'Central Asia', 'China, Hong Kong SAR', 
           'China, Macao SAR', 'China, mainland', 'China, Taiwan Province of', 
           'Eastern Africa', 'Eastern Asia', 'Eastern Europe', 'Ethiopia PDR',
           'Europe', 'European Union', 'Land Locked Developing Countries',
           'Least Developed Countries', 'Low Income Food Deficit Countries', 'Melanesia', 'Micronesia',
           'Middle Africa', 'Net Food Importing Developing Countries', 'Northern Africa', 'Northern America', 
           'Northern Europe', 'Oceania', 'Pacific Islands Trust Territory', 'Polynesia', 'Serbia and Montenegro', 'Small Island Developing States', 
           'South America', 'South-Eastern Asia', 'Southern Africa', 'Southern Asia', 'Southern Europe', 'Sudan (former)', 
           'USSR', 'Western Africa', 'Western Asia', 'Western Europe', 'World',
            ], axis=0, inplace=True) 
population_df

,Type,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Total Population - Both sexes,9169.410,9351.441,9543.205,9744.781,9956.320,10174.836,10399.926,10637.063,10893.776,...,31161.376,32269.589,33370.794,34413.603,35383.032,36296.113,37171.921,38041.754,38928.346,39835.428
Afghanistan,Total Population - Male,4730.250,4816.050,4907.030,5003.245,5104.765,5210.122,5319.123,5434.458,5559.836,...,15964.874,16554.278,17138.803,17686.166,18186.994,18651.985,19093.043,19529.727,19976.265,20434.981
Afghanistan,Total Population - Female,4439.156,4535.392,4636.170,4741.527,4851.553,4964.718,5080.813,5202.606,5333.936,...,15196.504,15715.314,16232.001,16727.437,17196.034,17644.126,18078.879,18512.030,18952.076,19400.447
Afghanistan,Rural population,8370.731,8507.016,8649.566,8798.496,8954.064,9113.479,9276.202,9446.519,9630.541,...,23280.663,23997.856,24703.798,25368.923,25985.093,26558.609,27099.874,27626.382,28150.604,28674.023
Afghanistan,Urban population,796.033,838.852,884.388,932.865,984.350,1038.852,1096.428,1157.827,1223.887,...,7416.295,7733.832,8054.222,8367.571,8670.939,8971.472,9273.302,9582.625,9904.337,10239.684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,Total Population - Both sexes,3905.034,4039.201,4178.726,4322.861,4471.177,4623.351,4779.827,4941.906,5111.337,...,13115.150,13350.373,13586.707,13814.629,14030.331,14236.595,14438.802,14645.468,14862.924,15092.171
Zimbabwe,Total Population - Male,1947.123,2014.035,2083.601,2155.402,2229.216,2304.832,2382.496,2462.904,2547.013,...,6240.533,6349.221,6459.915,6568.778,6674.206,6777.054,6879.119,6983.353,7092.010,7205.231
Zimbabwe,Total Population - Female,1957.915,2025.174,2095.125,2167.452,2241.962,2318.508,2397.329,2478.997,2564.313,...,6874.616,7001.157,7126.795,7245.864,7356.132,7459.545,7559.693,7662.120,7770.917,7886.940
Zimbabwe,Rural population,3374.502,3476.234,3571.594,3668.162,3765.445,3862.905,3960.880,4060.356,4163.930,...,9880.721,10138.667,10402.274,10667.966,10934.468,11201.138,11465.748,11725.970,11980.005,12226.340
Zimbabwe,Urban population,496.254,523.185,561.162,601.701,644.767,690.528,739.161,791.075,845.584,...,4830.105,4915.839,5009.401,5109.485,5215.894,5328.766,5447.513,5571.525,5700.460,5834.113

In [12]:
## Delete certain crop type.
population_df = population_df[population_df.Type != 'Total Population - Male']
population_df = population_df[population_df.Type != 'Total Population - Female']
population_df = population_df[population_df.Type != 'Rural population']
population_df = population_df[population_df.Type != 'Urban population']

# Delete unwanted columns
population_df.drop(
    columns=['Type'], axis=1, inplace=True)

population_df

,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,9169.410,9351.441,9543.205,9744.781,9956.320,10174.836,10399.926,10637.063,10893.776,11173.642,...,31161.376,32269.589,33370.794,34413.603,35383.032,36296.113,37171.921,38041.754,38928.346,39835.428
Albania,1685.936,1737.686,1790.573,1843.634,1896.171,1947.830,1998.740,2049.210,2099.729,2150.707,...,2914.096,2903.790,2896.305,2890.513,2886.438,2884.169,2882.740,2880.917,2877.797,2872.933
Algeria,11336.339,11619.828,11912.803,12221.675,12550.885,12902.627,13275.026,13663.583,14061.722,14464.985,...,37383.895,38140.133,38923.692,39728.025,40551.392,41389.189,42228.408,43053.054,43851.044,44616.624
American Samoa,20.602,21.253,22.034,22.854,23.672,24.462,25.248,25.989,26.703,27.363,...,55.667,55.713,55.791,55.812,55.741,55.620,55.465,55.312,55.191,55.100
Andorra,14.375,15.370,16.412,17.469,18.549,19.647,20.758,21.890,23.058,24.276,...,82.427,80.774,79.213,78.011,77.297,77.001,77.006,77.142,77.265,77.355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Western Sahara,35.724,38.849,42.308,46.314,50.970,56.626,63.125,69.476,74.337,76.874,...,495.773,504.858,514.995,526.216,538.749,552.615,567.402,582.463,597.339,611.875
Yemen,5393.036,5473.671,5556.766,5641.597,5727.751,5816.247,5907.874,6001.852,6097.035,6193.384,...,24473.178,25147.109,25823.485,26497.889,27168.208,27834.819,28498.683,29161.922,29825.964,30490.640
Yugoslav SFR,18726.796,18916.726,19104.322,19284.867,19455.329,19614.627,19765.042,19911.114,20059.084,20213.539,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Zambia,3164.329,3260.650,3360.104,3463.213,3570.464,3681.955,3797.873,3918.872,4045.740,4179.067,...,14465.150,14926.544,15399.788,15879.361,16363.458,16853.599,17351.708,17861.030,18383.955,18920.651
Zimbabwe,3905.034,4039.201,4178.726,4322.861,4471.177,4623.351,4779.827,4941.906,5111.337,5289.303,...,13115.150,13350.373,13586.707,13814.629,14030.331,14236.595,14438.802,14645.468,14862.924,15092.171

In [13]:
print(population_df.index.value_counts())

Afghanistan         1
Papua New Guinea    1
Nicaragua           1
Niger               1
Nigeria             1
                   ..
Gibraltar           1
Greece              1
Greenland           1
Grenada             1
Zimbabwe            1
Name: Country, Length: 235, dtype: int64

In [14]:
# Specify directory to output csv file
output_directory_path = "Data_Output"
file_name = "Population.csv"
file_path = os.path.join(output_directory_path, file_name)

In [16]:
# Output to csv file.
population_df.to_csv(file_path)